# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a908796e51ea20b32203f73a9b2728420fef91b518a7da6d03130c4e714ee4480d111ba045a3ac7a9ff898f81768f5929cd1c6b434bef0a2a2a1de8e1f5c2c40

test:
  secret_key_base: 3e94f5cbc2c38c1f2ca79e13870c014518a8a762c27ceccd89052589d7b5b0ca64c9455f93a45b1f7e992df1e1256ea2bede8f0a2e74dd69fc35c563d0c29830

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
